### ISSUE TITLE
Failed to run LADCF with vot-toolkit

### ISSUE THREAD

**Issue by addvaluejack** [XU-TIANYANG/LADCF_VOT#1]
Hello,

I failed to run LADCF vot-toolkit's _run_test.m_. The tracker successfully initialized at the first frame, I can see the tracking window and ground truth in the first frame. But it cashed at the second frame. Error code int Matlab's UI looks like this:

> CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Stopping watchdog thread
CLIENT: Trying to stop process using protocol.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited normally.
CLIENT: Closing server socket.
Tracker execution interrupted: Tracker process not alive
错误使用 traxclient
Tracker process not alive
出错 tracker_run (line 77)
data = traxclient(tracker.command, callback, ...
出错 workspace_test (line 53)
tracker_run(tracker, @callback, data);
出错 run_test (line 10)
workspace_test(tracker, sequences);

And the log file in _error_reports_ fold looks like this:
><a href="matlab:helpPopup MException" style="font-weight:bold">MException</a> (具有属性):
identifier: 'MATLAB:zeros:invalidStringInput'
message: 'CLASSNAME 输入必须为有效的数值或逻辑类名。'
cause: {0×1 cell}
stack: [3×1 struct]

Could anyone give me a hint about how to solve this problem? Thank you very much.

**Comment by XU-TIANYANG** [comment]
> Hello,
> 
> I failed to run LADCF vot-toolkit's _run_test.m_. The tracker successfully initialized at the first frame, I can see the tracking window and ground truth in the first frame. But it cashed at the second frame. Error code int Matlab's UI looks like this:
> 
> > CLIENT: Cleaning up.
> > CLIENT: Stopping logger thread
> > CLIENT: Stopping watchdog thread
> > CLIENT: Trying to stop process using protocol.
> > CLIENT: Flushing streams
> > CLIENT: Process should be terminated.
> > CLIENT: Stopping logger.
> > CLIENT: Tracker exited normally.
> > CLIENT: Closing server socket.
> > Tracker execution interrupted: Tracker process not alive
> > 错误使用 traxclient
> > Tracker process not alive
> > 出错 tracker_run (line 77)
> > data = traxclient(tracker.command, callback, ...
> > 出错 workspace_test (line 53)
> > tracker_run(tracker, @callback, data);
> > 出错 run_test (line 10)
> > workspace_test(tracker, sequences);
> 
> And the log file in _error_reports_ fold looks like this:
> 
> > MException (具有属性):
> > identifier: 'MATLAB:zeros:invalidStringInput'
> > message: 'CLASSNAME 输入必须为有效的数值或逻辑类名。'
> > cause: {0×1 cell}
> > stack: [3×1 struct]
> 
> Could anyone give me a hint about how to solve this problem? Thank you very much.

@addvaluejack , Could you provide the details in error_reports: err.stack.file and err.stack.line, then I can check the codes.

**Comment by addvaluejack** [comment]
@XU-TIANYANG Thanks for the fast reply.
_LADCF_VOT\implementation\tracker.m_ 
_line 59_

**Comment by XU-TIANYANG** [comment]
@addvaluejack Oh, I think you have choose a gpu device, but currently my code can only run on cpu.

**Comment by addvaluejack** [comment]
@XU-TIANYANG How can I force it to use cpu? I can't find gpu related settings in _VOT2018setting.m_.

**Comment by XU-TIANYANG** [comment]
@addvaluejack I have fixed this problem in init_default_params.m, thank you.
